### ISSUE TITLE
Update "Panel" to "Relay"

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/landing#11]
This button:
<img width="588" alt="Screen Shot 2022-07-13 at 3 18 45 PM" src="https://user-images.githubusercontent.com/5456408/178846575-7c7b7695-5335-48a4-b4ad-e778672f29e1.png">
should be updated to say "Relay" and should take you to relay.cc instead of daopanel.chat

**Comment by BrianS111** [comment]
Done 👍

**Comment by killthebuddh4** [comment]
Closing because this is a little bit stale :)
